import type { Note } from "@workspace/api-client-react";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const DEMO_NOTES: Note[] = [
  {
    id: 1,
    title: "Welcome to Graphe Notes 👋",
    content: `<h2>Welcome to Graphe Notes</h2><p>This is a demo — feel free to explore. Here's what you can do:</p><ul><li>Write and format notes with rich text</li><li>Pin important notes to the top</li><li>Organise with folders and tags</li><li>Search across all your notes instantly</li><li>Use the AI panel to summarise or rewrite</li></ul><p>Sign up to save your notes and access them anywhere.</p>`,
    contentText: "Welcome to Graphe Notes. This is a demo — feel free to explore.",
    pinned: true,
    favorite: false,
    vaulted: false,
    folderId: null,
    tags: ["demo"],
    coverImage: null,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 2,
    title: "Meeting notes — Product review",
    content: `<h2>Product Review — Q1</h2><p><strong>Attendees:</strong> Dee, Sarah, Marcus</p><h3>Agenda</h3><ul><li>Review Q1 metrics</li><li>Prioritise Q2 roadmap</li><li>Discuss user feedback</li></ul><h3>Key decisions</h3><p>Agreed to ship the new onboarding flow by end of month. Marcus to lead implementation. Sarah to draft copy.</p><p><strong>Next meeting:</strong> Thursday 10am</p>`,
    contentText: "Product Review Q1. Attendees: Dee, Sarah, Marcus.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: null,
    tags: ["work", "meetings"],
    coverImage: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 3,
    title: "Book notes — The Design of Everyday Things",
    content: `<h2>The Design of Everyday Things — Don Norman</h2><h3>Key concepts</h3><p><strong>Affordances</strong> — the perceived and actual properties of an object that suggest how it should be used.</p><p><strong>Signifiers</strong> — signals that communicate where actions should take place.</p><p><strong>Feedback</strong> — sending back information about what action has been done.</p><h3>Favourite quote</h3><blockquote>It is not the person who is at fault when something goes wrong — it is the design.</blockquote><h3>Rating</h3><p>⭐⭐⭐⭐⭐ — Essential reading for anyone building products.</p>`,
    contentText: "The Design of Everyday Things by Don Norman. Key concepts: affordances, signifiers, feedback.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: null,
    tags: ["books", "design"],
    coverImage: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 4,
    title: "App ideas 💡",
    content: `<h2>App ideas</h2><ul><li>A habit tracker that uses streaks but doesn't punish you for missing days</li><li>A recipe app that generates a shopping list automatically</li><li>A "done list" — instead of a to-do list, log what you've already accomplished</li><li>A journaling app with weekly AI-generated summaries</li><li>A focus timer that blocks distracting sites during sessions</li></ul>`,
    contentText: "App ideas. Habit tracker, recipe app, done list, journaling app, focus timer.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: null,
    tags: ["ideas"],
    coverImage: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },
  {
    id: 5,
    title: "Grocery list",
    content: `<h2>Grocery list</h2><ul><li>Olive oil</li><li>Sourdough bread</li><li>Eggs (free range)</li><li>Spinach</li><li>Cherry tomatoes</li><li>Parmesan</li><li>Pasta</li><li>Greek yoghurt</li><li>Oat milk</li><li>Dark chocolate</li></ul>`,
    contentText: "Grocery list. Olive oil, sourdough bread, eggs, spinach, cherry tomatoes, parmesan, pasta.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: null,
    tags: [],
    coverImage: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
];
