import type { Note, Folder, QuickBit } from "@workspace/api-client-react";
import type { NoteVersionFull } from "@/hooks/use-note-versions";

const now = new Date();
const ago = (d: number, h = 0) =>
  new Date(now.getTime() - d * 86400000 - h * 3600000).toISOString();
const inHours = (h: number) => new Date(now.getTime() + h * 3_600_000).toISOString();
const inDays = (d: number) => new Date(now.getTime() + d * 86_400_000).toISOString();

export const DEMO_FOLDERS: Folder[] = [
  {
    // Smart folder — auto-collects notes tagged work/meetings/clients/planning/ideas
    id: 1,
    name: "Work",
    parentId: null,
    color: "#3b82f6",
    icon: "briefcase",
    tagRules: ["work", "meetings", "clients", "planning", "ideas"],
    sortOrder: 0,
    createdAt: ago(60),
    updatedAt: ago(1),
  },
  {
    // Smart folder — auto-collects notes tagged personal/journal/recipes/health/shopping
    id: 2,
    name: "Personal",
    parentId: null,
    color: "#22c55e",
    icon: "heart",
    tagRules: ["personal", "journal", "recipes", "health", "shopping"],
    sortOrder: 1,
    createdAt: ago(60),
    updatedAt: ago(2),
  },
  {
    // Regular folder — notes manually moved here (folderId: 3)
    id: 3,
    name: "Archive",
    parentId: null,
    color: "#f59e0b",
    icon: "archive",
    tagRules: [],
    sortOrder: 2,
    createdAt: ago(90),
    updatedAt: ago(30),
  },
  {
    // Regular folder — notes manually moved here (folderId: 4)
    id: 4,
    name: "Reading List",
    parentId: null,
    color: "#ec4899",
    icon: "bookmark",
    tagRules: [],
    sortOrder: 3,
    createdAt: ago(20),
    updatedAt: ago(5),
  },
];

export const DEMO_NOTES: Note[] = [
  {
    id: 1,
    title: "Welcome to Graphe Notes 👋",
    content: `<h2>Welcome to Graphe Notes</h2><p>This is a demo — explore freely. Here's what you can do:</p><ul><li>Write and format notes with rich text</li><li>Organise with <strong>folders</strong> and <strong>tags</strong></li><li>Pin and favourite important notes</li><li>Search across everything instantly</li><li>Use the <strong>AI panel</strong> to summarise, rewrite, or brainstorm</li><li>Store sensitive notes in a <strong>vault</strong></li></ul><p>Sign up free to save your notes and access them from any device.</p>`,
    contentText: "Welcome to Graphe Notes. This is a demo — explore freely.",
    pinned: true,
    favorite: false,
    vaulted: false,
    folderId: null,
    tags: ["demo"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(0),
    updatedAt: ago(0),
  },
  {
    id: 2,
    title: "Q2 Product Roadmap",
    content: `<h2>Q2 Roadmap — Graphe</h2><p><strong>Theme:</strong> Growth & Retention</p><h3>🚀 Shipping in April</h3><ul><li>Onboarding redesign (Marcus)</li><li>Mobile push notifications</li><li>Tag autocomplete</li></ul><h3>📦 Shipping in May</h3><ul><li>Collaboration — shared notes</li><li>Web clipper browser extension</li><li>Export to PDF / Markdown</li></ul><h3>🔭 June (TBD)</h3><ul><li>AI-powered smart folders</li><li>Calendar integration</li></ul><h3>Success metrics</h3><p>D30 retention ≥ 40% · NPS ≥ 50 · 10k MAU by end of Q2</p>`,
    contentText: "Q2 Roadmap. Theme: Growth & Retention. Shipping in April: Onboarding redesign, mobile push notifications, tag autocomplete.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: 1,
    tags: ["work", "planning"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(14),
    updatedAt: ago(1),
  },
  {
    id: 3,
    title: "Weekly standup — 15 March",
    content: `<h2>Standup — 15 March</h2><p><strong>Done</strong></p><ul><li>Shipped tag autocomplete to staging ✅</li><li>Fixed editor crash on paste from Word ✅</li><li>Reviewed Sarah's onboarding copy ✅</li></ul><p><strong>Today</strong></p><ul><li>PR review for mobile notification service</li><li>Sync with design on empty states</li><li>Update error tracking dashboards</li></ul><p><strong>Blockers</strong></p><ul><li>Waiting on legal sign-off for the new ToS</li></ul>`,
    contentText: "Standup 15 March. Done: shipped tag autocomplete, fixed editor crash, reviewed onboarding copy.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 1,
    tags: ["work", "meetings"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(1),
    updatedAt: ago(0, 2),
  },
  {
    id: 4,
    title: "Client proposal — Nova Branding",
    content: `<h2>Nova Rebrand Proposal</h2><p><strong>Client:</strong> Nova Financial · <strong>Due:</strong> 22 March</p><h3>Scope</h3><ul><li>Brand strategy workshop (2 days)</li><li>Logo system + wordmark</li><li>Colour palette & typography</li><li>Brand guidelines document</li><li>Social media templates (10 formats)</li></ul><h3>Timeline</h3><p>Discovery → 2 weeks · Design → 3 weeks · Revisions → 1 week · Delivery → 1 week</p><h3>Investment</h3><p><strong>Total: £18,500</strong> (50% upfront, 50% on delivery)</p><h3>Next steps</h3><p>Send proposal PDF by Friday. Follow up call Monday 10am.</p>`,
    contentText: "Nova Rebrand Proposal. Client: Nova Financial. Scope includes brand strategy, logo system, brand guidelines.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 1,
    tags: ["work", "clients"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(4),
    updatedAt: ago(1),
  },
  {
    id: 5,
    title: "Side project ideas 💡",
    content: `<h2>Side project ideas</h2><p>Things worth building one day...</p><ul><li><strong>Quiet</strong> — a focus timer that locks distracting apps and logs your sessions</li><li><strong>Loopback</strong> — a journaling app that resurfaces old entries on the same date each year</li><li><strong>Shelf</strong> — a reading tracker with AI summaries and highlight extraction</li><li><strong>Nudge</strong> — a habit tracker that doesn't punish you for missing days</li><li><strong>Grain</strong> — a minimal recipe app that auto-generates shopping lists</li></ul><p>Strongest candidates: Loopback and Shelf — both scratch a personal itch.</p>`,
    contentText: "Side project ideas. Quiet focus timer, Loopback journaling, Shelf reading tracker, Nudge habit tracker, Grain recipe app.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: 1,
    tags: ["work", "ideas"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(10),
    updatedAt: ago(3),
  },
  {
    id: 6,
    title: "Journal — March 2026",
    content: `<h2>March 2026</h2><h3>March 14</h3><p>Good day overall. Got into a real flow state around 2pm — finished the proposal draft I'd been putting off. Went for a run after work, first one in two weeks. Need to make it a habit again.</p><h3>March 10</h3><p>Interesting conversation with Sam about the direction of the app. He thinks we're overcomplicating the onboarding. He might be right. The best products feel obvious in hindsight.</p><h3>March 5</h3><p>Started reading Atomic Habits again. The chapter on identity-based habits hit differently this time — "every action is a vote for the person you want to become." Going to write this somewhere visible.</p>`,
    contentText: "March 2026 journal. Good flow state. Went for a run. Conversation with Sam about onboarding.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 2,
    tags: ["journal"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(15),
    updatedAt: ago(0, 5),
  },
  {
    id: 7,
    title: "Bucket list",
    content: `<h2>Bucket list</h2><h3>Travel</h3><ul><li>See the northern lights in Iceland ❄️</li><li>Walk the Camino de Santiago</li><li>Road trip across Japan 🇯🇵</li><li>Safari in Botswana</li></ul><h3>Experiences</h3><ul><li>Learn to surf properly</li><li>Complete a triathlon</li><li>Take a pottery class</li><li>Spend a month somewhere I've never been with no plans</li></ul><h3>Creative</h3><ul><li>Write and finish a short story</li><li>Record an album (even a bad one)</li><li>Build something with my hands — a table, a shelf, anything</li></ul>`,
    contentText: "Bucket list. Travel: northern lights, Camino de Santiago, Japan road trip. Experiences: learn to surf, triathlon.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: 2,
    tags: ["personal"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(45),
    updatedAt: ago(7),
  },
  {
    id: 8,
    title: "Recipe — Pasta al limone",
    content: `<h2>Pasta al limone 🍋</h2><p><em>Serves 2 · 20 minutes</em></p><h3>Ingredients</h3><ul><li>200g spaghetti or linguine</li><li>1 large lemon (zest + juice)</li><li>60ml double cream</li><li>40g Parmesan, finely grated</li><li>2 tbsp butter</li><li>Salt, black pepper</li><li>Handful of fresh basil</li></ul><h3>Method</h3><ol><li>Cook pasta in well-salted water until al dente. Reserve 1 cup pasta water.</li><li>Melt butter in a wide pan over low heat. Add lemon zest, cook 1 min.</li><li>Add cream and half the pasta water. Simmer gently 2 mins.</li><li>Add drained pasta, Parmesan and lemon juice. Toss vigorously.</li><li>Add more pasta water to loosen if needed. Season generously.</li><li>Finish with basil and extra Parmesan.</li></ol><p><strong>Tip:</strong> Don't rush the sauce — keep the heat low and let the starch from the pasta water do the work.</p>`,
    contentText: "Pasta al limone recipe. Serves 2. 20 minutes. Spaghetti, lemon, cream, Parmesan, butter.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 3,
    tags: ["recipes"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(20),
    updatedAt: ago(20),
  },
  {
    id: 9,
    title: "Fitness goals — 2026",
    content: `<h2>Fitness goals 2026</h2><h3>Primary goal</h3><p>Run a sub-50min 10k by September.</p><h3>Weekly targets</h3><ul><li>Run 3x per week (Mon, Wed, Sat)</li><li>Strength training 2x per week</li><li>10,000 steps daily average</li><li>In bed by 10:30pm on weeknights</li></ul><h3>Progress</h3><p>Current 10k PB: 54:32 (Feb 2026)</p><p>March: 3/3 weeks on track ✅</p><h3>Notes</h3><p>The morning runs are better. Stop negotiating with yourself the night before — just set the alarm and go.</p>`,
    contentText: "Fitness goals 2026. Run a sub-50min 10k by September. Run 3x per week, strength training 2x.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 2,
    tags: ["health", "personal"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(75),
    updatedAt: ago(5),
  },
  {
    id: 10,
    title: "Book notes — Atomic Habits",
    content: `<h2>Atomic Habits — James Clear</h2><h3>Core idea</h3><p>Small habits compound into remarkable results. A 1% improvement every day = 37x better after a year.</p><h3>The Four Laws</h3><ol><li><strong>Make it obvious</strong> — design your environment to surface cues</li><li><strong>Make it attractive</strong> — pair habits with things you enjoy</li><li><strong>Make it easy</strong> — reduce friction to two minutes or less</li><li><strong>Make it satisfying</strong> — reward yourself immediately</li></ol><h3>Best quotes</h3><blockquote>"You don't rise to the level of your goals. You fall to the level of your systems."</blockquote><blockquote>"Every action is a vote for the type of person you wish to become."</blockquote><h3>My takeaways</h3><ul><li>Identity change > outcome goals</li><li>The plateau of latent potential — results come after the work, not during</li><li>Never miss twice — one missed day is an accident, two is a new habit</li></ul>`,
    contentText: "Atomic Habits by James Clear. Core idea: small habits compound. The Four Laws: obvious, attractive, easy, satisfying.",
    pinned: false,
    favorite: true,
    vaulted: false,
    folderId: 4,
    tags: ["books"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(18),
    updatedAt: ago(6),
  },
  {
    id: 11,
    title: "Spanish — Week 8 🇪🇸",
    content: `<h2>Spanish progress — Week 8</h2><p><strong>App:</strong> Duolingo + Pimsleur · <strong>Streak:</strong> 54 days</p><h3>This week</h3><ul><li>Finished the travel unit on Duolingo</li><li>Completed Pimsleur lessons 36–40</li><li>First proper conversation with a native speaker on HelloTalk (very broken but it happened!)</li></ul><h3>New vocabulary</h3><ul><li>sin embargo — nevertheless</li><li>de hecho — in fact</li><li>a pesar de — in spite of</li><li>aunque — although / even though</li></ul><h3>Goals for week 9</h3><ul><li>Get through the subjunctive intro</li><li>Watch one episode of a Spanish show without subtitles</li></ul>`,
    contentText: "Spanish Week 8. Duolingo + Pimsleur. 54 day streak. First real conversation with a native speaker.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 3,
    tags: ["languages"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(8),
    updatedAt: ago(1),
  },
  {
    id: 12,
    title: "CSS tricks worth remembering",
    content: `<h2>CSS tricks worth remembering</h2><h3>Layout</h3><pre><code>/* Perfect centering */
.container {
  display: grid;
  place-items: center;
}

/* Responsive without media queries */
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
}</code></pre><h3>Typography</h3><pre><code>/* Fluid type scale */
font-size: clamp(1rem, 2.5vw, 1.5rem);

/* Better text rendering */
-webkit-font-smoothing: antialiased;</code></pre><h3>Useful selectors</h3><pre><code>/* Style first paragraph after heading */
h2 + p { ... }

/* Every odd card */
.card:nth-child(odd) { ... }</code></pre>`,
    contentText: "CSS tricks. Perfect centering with grid. Responsive layouts without media queries. Fluid typography with clamp.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: 4,
    tags: ["dev", "learning"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(22),
    updatedAt: ago(9),
  },
  {
    id: 13,
    title: "Japan trip — May 2026 🗾",
    content: `<h2>Japan — May 2026</h2><p><strong>Dates:</strong> 2–22 May · <strong>Cities:</strong> Tokyo → Kyoto → Osaka → Hiroshima → Tokyo</p><h3>Tokyo (2–8 May)</h3><ul><li>Shibuya, Shinjuku, Harajuku</li><li>TeamLab Borderless (book now!)</li><li>Day trip to Nikko</li><li>Ramen in Fuunji — arrive early</li></ul><h3>Kyoto (9–14 May)</h3><ul><li>Fushimi Inari at sunrise</li><li>Arashiyama bamboo grove + monkey park</li><li>Nishiki Market</li><li>Tea ceremony in Gion</li></ul><h3>Osaka (15–18 May)</h3><ul><li>Dotonbori street food</li><li>Day trip to Nara — feed the deer</li></ul><h3>To book</h3><ul><li>Flights ✅</li><li>JR Pass ✅</li><li>Accommodation — Kyoto still needed</li><li>TeamLab tickets</li></ul>`,
    contentText: "Japan trip May 2026. Tokyo, Kyoto, Osaka, Hiroshima. TeamLab Borderless, Fushimi Inari at sunrise, Arashiyama.",
    pinned: true,
    favorite: true,
    vaulted: false,
    folderId: null,
    tags: ["travel", "planning"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(30),
    updatedAt: ago(2),
  },
  {
    id: 14,
    title: "Weekly groceries",
    content: `<h2>Groceries — this week</h2><h3>Produce</h3><ul><li>Spinach</li><li>Cherry tomatoes</li><li>Avocados (×3)</li><li>Lemons (×4)</li><li>Garlic</li><li>Red onion</li></ul><h3>Fridge</h3><ul><li>Eggs (free range, ×12)</li><li>Greek yoghurt</li><li>Oat milk (×2)</li><li>Parmesan</li><li>Butter</li></ul><h3>Pantry</h3><ul><li>Spaghetti</li><li>Olive oil (nearly out)</li><li>Tinned tomatoes (×4)</li><li>Arborio rice</li><li>Dark chocolate</li></ul>`,
    contentText: "Groceries. Spinach, cherry tomatoes, avocados, eggs, Greek yoghurt, oat milk, spaghetti, olive oil.",
    pinned: false,
    favorite: false,
    vaulted: false,
    folderId: null,
    tags: ["shopping"],
    coverImage: null,
    deletedAt: null,
    autoDeleteAt: null,
    deletedReason: null,
    createdAt: ago(1),
    updatedAt: ago(0, 1),
  },
];

// IDs start at 101 so they don't collide with real QB IDs in any shared query cache
export const DEMO_QUICK_BITS: QuickBit[] = [
  {
    id: 101,
    userId: null,
    title: "Grab dry cleaning 🧺",
    content: "<p>Ready for pickup — they close at <strong>6:30pm tonight</strong>. Already paid, just show the ticket in the app.</p>",
    contentText: "Ready for pickup — they close at 6:30pm tonight. Already paid, just show the ticket.",
    expiresAt: inHours(3),
    notificationHours: [1],
    createdAt: ago(0),
    updatedAt: ago(0),
  },
  {
    id: 102,
    userId: null,
    title: "Hotel wifi — Edinburgh",
    content: "<p><strong>Network:</strong> Marriott_Guests</p><p><strong>Password:</strong> edinburgh2026</p><p>Room 614 · Check out Sunday</p>",
    contentText: "Network: Marriott_Guests / Password: edinburgh2026. Room 614. Check out Sunday.",
    expiresAt: inHours(18),
    notificationHours: [2],
    createdAt: ago(1),
    updatedAt: ago(1),
  },
  {
    id: 103,
    userId: null,
    title: "Sprint review talking points",
    content: "<ul><li>Lead with the onboarding redesign — it's the strongest change</li><li>Show the 40% drop in support tickets after the fix</li><li>Be upfront about the auth delay — propose pushing to next sprint</li><li>Use mobile screenshots, not desktop</li></ul>",
    contentText: "Lead with onboarding redesign. Highlight 40% drop in support tickets. Be upfront about auth delay.",
    expiresAt: inDays(2),
    notificationHours: [4, 24],
    createdAt: ago(0),
    updatedAt: ago(0),
  },
  {
    id: 104,
    userId: null,
    title: "Book Lisbon flights ✈️",
    content: "<p>Sale ends <strong>Friday midnight</strong> — prices jump after that.</p><p>Dates: 14–21 June · Budget: under £180 return · Check Skyscanner and Google Flights.</p>",
    contentText: "Sale ends Friday midnight. Dates: 14–21 June. Budget: under £180 return.",
    expiresAt: inDays(4),
    notificationHours: [24, 48],
    createdAt: ago(2),
    updatedAt: ago(2),
  },
  {
    id: 105,
    userId: null,
    title: "Flatmate door code",
    content: "<p>Main entrance: <strong>#1847</strong></p><p>Resets Sunday — ask Jamie for the new one before then.</p>",
    contentText: "Main entrance: #1847. Resets Sunday — ask Jamie for the new one before then.",
    expiresAt: inDays(6),
    notificationHours: [24],
    createdAt: ago(1),
    updatedAt: ago(1),
  },
];

export const DEMO_TAGS: string[] = [
  "demo", "work", "planning", "meetings", "clients", "ideas",
  "journal", "personal", "recipes", "health", "books",
  "learning", "languages", "dev", "travel", "shopping",
];

// Pre-seeded version history for the demo. Newest first within each note's
// list (matches what the API returns). IDs start above 100k so they don't
// collide with anything created during a session — see
// `seedDemoVersionIdCounter()` in `use-note-versions.ts`.
export const DEMO_NOTE_VERSIONS: Record<number, NoteVersionFull[]> = {
  // Q2 Roadmap — show a Pre-AI snapshot, a manual save, and an auto-save.
  2: [
    {
      id: 100_003,
      noteId: 2,
      title: "Q2 Product Roadmap",
      content: `<h2>Q2 Roadmap — Graphe</h2><p><strong>Theme:</strong> Growth & Retention</p><h3>🚀 Shipping in April</h3><ul><li>Onboarding redesign (Marcus)</li><li>Mobile push notifications</li></ul><h3>📦 Shipping in May</h3><ul><li>Collaboration — shared notes</li><li>Web clipper browser extension</li></ul>`,
      contentText:
        "Q2 Roadmap. Theme: Growth & Retention. Shipping in April: Onboarding redesign, mobile push notifications.",
      label: null,
      source: "auto_save",
      createdAt: ago(1),
    },
    {
      id: 100_002,
      noteId: 2,
      title: "Q2 Product Roadmap (draft)",
      content: `<h2>Q2 Roadmap — Graphe</h2><p><strong>Theme:</strong> Growth and Retention</p><h3>April</h3><ul><li>Onboarding redesign</li><li>Push notifications</li></ul><h3>May</h3><ul><li>Shared notes</li></ul>`,
      contentText:
        "Q2 Roadmap. Theme: Growth and Retention. April: Onboarding redesign, push notifications. May: Shared notes.",
      label: "Before AI rewrite",
      source: "pre_ai_rewrite",
      createdAt: ago(2),
    },
    {
      id: 100_001,
      noteId: 2,
      title: "Q2 Roadmap — first pass",
      content: `<h2>Q2 Roadmap</h2><p>Theme: growth.</p><ul><li>Onboarding</li><li>Push</li><li>Shared notes</li></ul>`,
      contentText: "Q2 Roadmap. Theme: growth. Onboarding, push, shared notes.",
      label: "Initial outline",
      source: "manual_save",
      createdAt: ago(7),
    },
  ],
  // Welcome note — single auto snapshot so the panel isn't empty everywhere.
  1: [
    {
      id: 100_010,
      noteId: 1,
      title: "Welcome to Graphe Notes",
      content: `<h2>Welcome to Graphe Notes</h2><p>This is a demo — explore freely.</p>`,
      contentText: "Welcome to Graphe Notes. This is a demo — explore freely.",
      label: null,
      source: "auto_save",
      createdAt: ago(0, 2),
    },
  ],
};
